# Пример конфигурации валидации чеков
# Скопируйте этот файл в validation_config.yaml и настройте под свои нужды

validation:
  # Минимальная уверенность OCR (0-100%)
  min_confidence: 50.0
  
  # Толерантность для сравнения сумм (в рублях)
  amount_tolerance: 0.01

# Настройки валидации телефонов
phone_validation:
  # Валидные номера телефонов (поддерживаются различные форматы)
  valid_phones:
    - '79879335515'      # Полный номер без разделителей
    - '+79879335515'     # С международным кодом
    - '89879335515'      # С кодом 8
    - '7 987 933 55 15'  # С пробелами
    - '7-987-933-55-15'  # С тире
    - '7(987)933-55-15'  # Со скобками и тире
    - '8 987 933 55 15'  # С кодом 8 и пробелами
    - '8-987-933-55-15'  # С кодом 8 и тире
    - '8(987)933-55-15'  # С кодом 8, скобками и тире

  # Паттерны для поиска номеров телефонов
  patterns:
    - pattern: '\\+?7[\\s\\-\\(\\)]?9\\d{2}[\\s\\-\\(\\)]?\\d{3}[\\s\\-\\(\\)]?\\d{2}[\\s\\-\\(\\)]?\\d{2}'
      description: 'Российский номер с +7'
      country_code: '+7'
    - pattern: '8[\\s\\-\\(\\)]?9\\d{2}[\\s\\-\\(\\)]?\\d{3}[\\s\\-\\(\\)]?\\d{2}[\\s\\-\\(\\)]?\\d{2}'
      description: 'Российский номер с 8'
      country_code: '8'
    - pattern: '9\\d{9}'
      description: 'Российский номер без кода'
      country_code: '7'

# Настройки валидации сумм
amount_validation:
  # Валидные суммы (поддерживаются различные форматы)
  valid_amounts:
    - 1500.00
    - 1500
    - 1500.0
    - 2000.00
    - 3000.0
    - 5000

  # Паттерны для поиска сумм
  patterns:
    - pattern: '(\\d+(?:[.,]\\d{2})?)\\s*(?:руб|₽|rub|р\\.|Р)'
      description: 'Сумма с валютой'
    - pattern: '(\\d+)\\s*Р'
      description: 'Сумма с большой Р'
    - pattern: '(\\d+)\\s*р'
      description: 'Сумма с маленькой р'
    - pattern: '(\\d+)\\s*руб'
      description: 'Сумма с "руб"'
    - pattern: '(\\d+)\\s*₽'
      description: 'Сумма с символом рубля'
    - pattern: '(?:сумма|итого|к оплате)[\\s:]*(\\d+(?:[.,]\\d{2})?)'
      description: 'Сумма с ключевыми словами'
    - pattern: '(?:перевод|платеж|оплата)[\\s:]*(\\d+(?:[.,]\\d{2})?)'
      description: 'Сумма с глаголами'

# Настройки валидации банковских счетов и карт
account_validation:
  # Валидные банковские счета (20 цифр)
  valid_accounts:
    - '40817810099910004312'
    - '40817810099910004313'
    - '12345678901234567890'

  # Валидные номера карт (16 цифр)
  valid_cards:
    - '2200590431900533'
    - '1234567890123456'
    - '5555555555554444'

  # Паттерны для поиска счетов и карт
  patterns:
    - pattern: '\\b\\d{20}\\b'
      description: '20-значный банковский счет'
      type: 'account'
    - pattern: '\\b\\d{16}\\b'
      description: '16-значный номер карты'
      type: 'card'
    - pattern: '\\b\\d{4}[\\s\\-]?\\d{4}[\\s\\-]?\\d{4}[\\s\\-]?\\d{4}\\b'
      description: 'Номер карты с разделителями'
      type: 'card'

# Настройки парсинга дат
date_validation:
  # Паттерны для поиска дат
  patterns:
    - pattern: '\\b\\d{1,2}[./]\\d{1,2}[./]\\d{4}\\b'
      description: 'Дата в формате ДД.ММ.ГГГГ или ДД/ММ/ГГГГ'
    - pattern: '\\b\\d{1,2}\\s+(?:января|февраля|марта|апреля|мая|июня|июля|августа|сентября|октября|ноября|декабря)\\s+\\d{4}\\b'
      description: 'Дата с названием месяца'

# Настройки парсинга времени
time_validation:
  # Паттерны для поиска времени
  patterns:
    - pattern: '\\b\\d{1,2}:\\d{2}(?::\\d{2})?\\b'
      description: 'Время в формате ЧЧ:ММ или ЧЧ:ММ:СС'

# Настройки логирования
logging:
  level: 'INFO'  # DEBUG, INFO, WARNING, ERROR
  file: 'logs/bot.log'
  max_size: '10MB'
  backup_count: 5

# Настройки безопасности
security:
  # Максимальный размер файла (в байтах)
  max_file_size: 20971520  # 20 MB
  
  # Поддерживаемые форматы изображений
  supported_image_formats: ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
  
  # Поддерживаемые форматы документов
  supported_document_formats: ['.pdf']
  
  # Таймаут обработки (в секундах)
  processing_timeout: 30
